language: bash

services:
  - docker

env:
  global:
  - REPO=${TRAVIS_REPO_SLUG}

script:
    - docker build -t $REPO:latest .
    #  - docker pull $REPO:latest
    #  - docker build --cache-from $REPO:latest -t $REPO:latest .

after_success:
    - if [ -n "$TRAVIS_TAG" ]; then
        echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin;
        docker tag $REPO:latest $REPO:$TRAVIS_TAG;
        docker push $REPO;
      else
        echo "not a tag branch, skip deploy...";
      fi

